# Generated by Django 6.0.1 on 2026-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
