# Generated by Django 6.0.1 on 2026-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_sentiment_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="budget",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="service",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="urgency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="enquiry_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
