# Generated by Django 6.0.1 on 2026-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_budget_lead_service_lead_urgency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
