# Generated by Django 6.0.1 on 2026-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_lead_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(default=0),
        ),
    ]
