# Generated by Django 6.0.1 on 2026-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20),
        ),
    ]
