# Generated by Django 6.0.1 on 2026-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_lead_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="enquiry_text",
            new_name="project_details",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="email",
            new_name="work_email",
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_inr_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="country",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("UAE", "United Arab Emirates"),
                    ("DE", "Germany"),
                    ("UK", "United Kingdom"),
                    ("IN", "India"),
                    ("Other", "Other"),
                ],
                default="IN",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="interest",
            field=models.CharField(
                choices=[
                    ("AI_STRAT", "AI Strategy & Consulting"),
                    ("GEN_AI", "Generative AI Solutions"),
                    ("AI_ENG", "AI Engineering & MLOps"),
                    ("AGENT_ORCH", "Autonomous Agent Orchestration"),
                    ("AI_AUTO", "AI Workflow Automation"),
                    ("DRONE", "Autonomous Drone Solutions"),
                    ("FULL_STACK", "Full Stack Development"),
                    ("DIGITAL_MKT", "AI Digital Marketing"),
                    ("GCC", "GCC Setup"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lead",
            name="budget",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Negotiation", "Negotiation"),
                    ("Closed", "Closed"),
                ],
                default="New",
                max_length=20,
            ),
        ),
    ]
