# Generated by Django 6.0.3 on 2026-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_assigned_user_lead_conversion_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('assignment_change', 'Assignment Changed'), ('note_added', 'Note Added'), ('system_update', 'System Update')], default='system_update', max_length=50),
        ),
    ]
