# Generated by Django 6.0.3 on 2026-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_fix_probabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(choices=[('AI_STRAT', 'AI Strategy & Consulting'), ('GEN_AI', 'Generative AI Solutions'), ('AI_ENG', 'AI Engineering & MLOps'), ('AGENT_ORCH', 'Autonomous Agents'), ('AI_AUTO', 'Workflows & Automation'), ('DRONE', 'Autonomous Drone Solutions'), ('FULL_STACK', 'Full Stack Development'), ('DIGITAL_MKT', 'AI Digital Marketing'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
